name: disney
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  gradient_borders: ^1.0.0
  http: ^1.1.0
  intl: ^0.18.1
  url_launcher: ^6.1.12
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
